// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as embed$0 from "../../../embed/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as faxmanager$0 from "./internal/faxmanager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "./internal/music/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as status$0 from "./internal/status/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTrackToPlaylist adds track to playlist
 * @param {string} playlistID
 * @param {string} trackID
 * @param {number} position
 * @returns {$CancellablePromise<void>}
 */
export function AddTrackToPlaylist(playlistID, trackID, position) {
    return $Call.ByID(1914060488, playlistID, trackID, position);
}

/**
 * ClearAllCache 全キャッシュをクリア
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllCache() {
    return $Call.ByID(1065994017);
}

/**
 * CloseNotification closes the notification window
 * @returns {$CancellablePromise<void>}
 */
export function CloseNotification() {
    return $Call.ByID(2151220900);
}

/**
 * ConnectPrinter connects to the printer with the given address
 * @param {string} address
 * @returns {$CancellablePromise<void>}
 */
export function ConnectPrinter(address) {
    return $Call.ByID(1365609627, address);
}

/**
 * CreateMusicPlaylist creates a new playlist
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<music$0.Playlist | null>}
 */
export function CreateMusicPlaylist(name, description) {
    return $Call.ByID(250164362, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteFont deletes the custom font
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFont() {
    return $Call.ByID(3590328019);
}

/**
 * DeleteMusicPlaylist deletes a playlist
 * @param {string} playlistID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMusicPlaylist(playlistID) {
    return $Call.ByID(1111099855, playlistID);
}

/**
 * DeleteMusicTrack deletes a track
 * @param {string} trackID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMusicTrack(trackID) {
    return $Call.ByID(2299354664, trackID);
}

/**
 * DisconnectPrinter disconnects from the printer
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectPrinter() {
    return $Call.ByID(3424728709);
}

/**
 * GenerateFontPreview generates a preview image with the current font
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function GenerateFontPreview(text) {
    return $Call.ByID(693336333, text);
}

/**
 * GetAllSettings returns all application settings from database
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetAllSettings() {
    return $Call.ByID(1224888095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAuthURL returns the Twitch OAuth URL
 * @returns {$CancellablePromise<string>}
 */
export function GetAuthURL() {
    return $Call.ByID(1157698938);
}

/**
 * GetCacheSettings キャッシュ設定を取得
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetCacheSettings() {
    return $Call.ByID(3406065454).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCacheStats キャッシュ統計を取得
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetCacheStats() {
    return $Call.ByID(140485022).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetEventSubStatus returns the current EventSub connection status
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetEventSubStatus() {
    return $Call.ByID(2198043831).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFeatureStatus returns the feature status from database
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetFeatureStatus() {
    return $Call.ByID(756967557).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetMusicPlaylists returns all playlists for settings page
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetMusicPlaylists() {
    return $Call.ByID(2659278197).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetMusicTracks returns all tracks for settings page
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetMusicTracks() {
    return $Call.ByID(2577392278).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPlaylistTracks returns tracks in a playlist for settings page
 * @param {string} playlistID
 * @returns {$CancellablePromise<(music$0.PlaylistTrack | null)[]>}
 */
export function GetPlaylistTracks(playlistID) {
    return $Call.ByID(1686893209, playlistID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPrinterStatus returns the current printer connection status
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetPrinterStatus() {
    return $Call.ByID(2965661891).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetRecentFaxes returns recent fax messages
 * @param {number} limit
 * @returns {$CancellablePromise<(faxmanager$0.Fax | null)[]>}
 */
export function GetRecentFaxes(limit) {
    return $Call.ByID(123550887, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetScreens returns all available screens
 * @returns {$CancellablePromise<$models.Screen[]>}
 */
export function GetScreens() {
    return $Call.ByID(2771281520).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetScreensExtended returns all screens with their absolute positions
 * @returns {$CancellablePromise<$models.ScreenInfoExtended[]>}
 */
export function GetScreensExtended() {
    return $Call.ByID(4216401441).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetServerPort returns the current server port
 * @returns {$CancellablePromise<number>}
 */
export function GetServerPort() {
    return $Call.ByID(1323345775);
}

/**
 * GetServerStatus returns the status of internal servers
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetServerStatus() {
    return $Call.ByID(880383150).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSettings returns the current application settings
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetStreamStatus returns the current stream status
 * @returns {$CancellablePromise<status$0.StreamStatus>}
 */
export function GetStreamStatus() {
    return $Call.ByID(422925209).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetTrackArtwork returns track artwork as base64 encoded data URL
 * @param {string} trackID
 * @returns {$CancellablePromise<string>}
 */
export function GetTrackArtwork(trackID) {
    return $Call.ByID(172201974, trackID);
}

/**
 * GetVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * GetWindowPosition returns the saved window position and size
 * @returns {$CancellablePromise<{ [_: string]: number }>}
 */
export function GetWindowPosition() {
    return $Call.ByID(1683686380).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * HandleAuthCallback handles the OAuth callback
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function HandleAuthCallback(code) {
    return $Call.ByID(546744214, code);
}

/**
 * ReconnectPrinter forces a complete reconnection to the printer
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectPrinter() {
    return $Call.ByID(1952201938);
}

/**
 * RemoveTrackFromPlaylist removes track from playlist
 * @param {string} playlistID
 * @param {string} trackID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTrackFromPlaylist(playlistID, trackID) {
    return $Call.ByID(3077703482, playlistID, trackID);
}

/**
 * ResetNotificationWindowPosition 通知ウィンドウの保存された位置をクリア
 * @returns {$CancellablePromise<void>}
 */
export function ResetNotificationWindowPosition() {
    return $Call.ByID(844694436);
}

/**
 * RunCacheCleanup キャッシュクリーンアップを実行
 * @returns {$CancellablePromise<void>}
 */
export function RunCacheCleanup() {
    return $Call.ByID(768465196);
}

/**
 * SaveWindowPosition saves the window position and size to database
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowPosition(x, y, width, height) {
    return $Call.ByID(3693895983, x, y, width, height);
}

/**
 * ScanBluetoothDevices scans for nearby Bluetooth devices
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function ScanBluetoothDevices() {
    return $Call.ByID(3590303845).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * SetWebAssets sets the embedded web assets for the web server
 * @param {embed$0.FS | null} assets
 * @returns {$CancellablePromise<void>}
 */
export function SetWebAssets(assets) {
    return $Call.ByID(1809151378, assets);
}

/**
 * TestChannelPointRedemption テスト用のチャンネルポイント報酬を発行
 * @param {string} userInput
 * @param {string} userName
 * @param {string} rewardTitle
 * @returns {$CancellablePromise<void>}
 */
export function TestChannelPointRedemption(userInput, userName, rewardTitle) {
    return $Call.ByID(3159609875, userInput, userName, rewardTitle);
}

/**
 * TestNotification sends a test notification
 * @returns {$CancellablePromise<void>}
 */
export function TestNotification() {
    return $Call.ByID(2373108510);
}

/**
 * TestPrint sends a test pattern to the printer
 * @returns {$CancellablePromise<void>}
 */
export function TestPrint() {
    return $Call.ByID(3301605152);
}

/**
 * UpdateCacheSettings キャッシュ設定を更新
 * @param {{ [_: string]: any }} settingsMap
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCacheSettings(settingsMap) {
    return $Call.ByID(3284314243, settingsMap);
}

/**
 * UpdateSettings updates application settings
 * @param {{ [_: string]: any }} newSettings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(newSettings) {
    return $Call.ByID(2894041249, newSettings);
}

/**
 * UploadFont uploads a font file
 * @param {string} filename
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function UploadFont(filename, base64Data) {
    return $Call.ByID(1497425873, filename, base64Data);
}

// Private type creation functions
const $$createType0 = music$0.Playlist.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = music$0.PlaylistTrack.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = faxmanager$0.Fax.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.Screen.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.ScreenInfoExtended.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = status$0.StreamStatus.createFrom;
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = $Create.Array($$createType2);
