// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TODO(v3): Temporary stub for runtime.Screen - replace with proper v3 screen API
 */
export class Screen {
    /**
     * Creates a new Screen instance.
     * @param {Partial<Screen>} [$$source = {}] - The source object to create the Screen.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Height"] = 0;
        }
        if (!("IsPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Screen instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Screen}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Screen(/** @type {Partial<Screen>} */($$parsedSource));
    }
}

/**
 * ScreenInfoExtended represents screen information with position
 */
export class ScreenInfoExtended {
    /**
     * Creates a new ScreenInfoExtended instance.
     * @param {Partial<ScreenInfoExtended>} [$$source = {}] - The source object to create the ScreenInfoExtended.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenInfoExtended instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenInfoExtended}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenInfoExtended(/** @type {Partial<ScreenInfoExtended>} */($$parsedSource));
    }
}
