import type React from 'react';
import type { ChattersPanelChatter } from '../ChattersPanel';
import type { ChatMessage } from '../ChatSidebarItem';
import type { RichChatInputRef } from '../chat/RichChatInput';
import type {
  BadgeVisual,
  ChatDisplayMode,
  ChatDisplayItem,
  UserInfoPopupState,
} from './types';

export type ChatSidebarLayoutProps = {
  asideClass: string;
  sidebarStyle: React.CSSProperties;
  embedded: boolean;
  wrapperClass: string;
  isCollapsed: boolean;
  resizeHandleSideClass: string;
  handleResizeStart: (event: React.PointerEvent<HTMLDivElement>) => void;
  panelClass: string;
  activeTab: string;
  activeChatDisplayMode: ChatDisplayMode;
  messageOrderReversed: boolean;
  chattersOpen: boolean;
  channelEditorOpen: boolean;
  actionsMenuOpen: boolean;
  settingsOpen: boolean;
  popoutChatUrl: string;
  toggleIcon: React.ReactNode;
  fontSize: number;
  translationEnabled: boolean;
  notificationOverwrite: boolean;
  onEnsureIrcPreview?: (channelLogin: string) => void;
  setChannelEditorOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setChannelInputError: React.Dispatch<React.SetStateAction<string>>;
  setMessageOrderReversedByTab: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  setChattersOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setActiveChatDisplayMode: (mode: ChatDisplayMode) => void;
  setActionsMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setEmbedReloadNonceByTab: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  setSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  handleOpenChatPopout: () => void;
  onFontSizeChange: (size: number) => void;
  onTranslationToggle: (enabled: boolean) => void;
  onNotificationModeToggle: (enabled: boolean) => void;
  handleToggle: () => void;
  settingsButtonRef: React.MutableRefObject<HTMLButtonElement | null>;
  settingsPanelRef: React.MutableRefObject<HTMLDivElement | null>;
  actionsMenuButtonRef: React.MutableRefObject<HTMLButtonElement | null>;
  actionsMenuPanelRef: React.MutableRefObject<HTMLDivElement | null>;
  tabScrollerRef: React.MutableRefObject<HTMLDivElement | null>;
  tabButtonRefs: React.MutableRefObject<Record<string, HTMLButtonElement | null>>;
  tabs: Array<{ id: string; label: string; title: string; removable: boolean }>;
  connectingChannels: Record<string, boolean>;
  channelInput: string;
  channelInputError: string;
  setActiveTab: React.Dispatch<React.SetStateAction<string>>;
  handleRemoveChannel: (channel: string) => void;
  setChannelInput: React.Dispatch<React.SetStateAction<string>>;
  handleAddChannel: () => void;
  embedFrames: Array<{ tabId: string; channelLogin: string; src: string }>;
  activeEmbedFrame: { tabId: string; channelLogin: string; src: string } | null;
  listRef: React.MutableRefObject<HTMLDivElement | null>;
  activeMessages: ChatMessage[];
  emptyState: React.ReactNode;
  displayedItems: ChatDisplayItem[];
  metaFontSize: number;
  translationFontSize: number;
  handleOpenUserInfo: (message: ChatMessage) => void;
  handleOpenRawData: (message: ChatMessage) => void;
  resolveBadgeVisual: (badgeKey: string) => BadgeVisual | null;
  richInputRef: React.MutableRefObject<RichChatInputRef | null>;
  postingMessage: boolean;
  isPrimaryTab: boolean;
  primaryChannelLogin: string;
  activeBadgeChannelLogin: string;
  postError: string;
  setPostError: React.Dispatch<React.SetStateAction<string>>;
  setInputHasContent: React.Dispatch<React.SetStateAction<boolean>>;
  sendComment: () => Promise<void>;
  inputHasContent: boolean;
  fallbackChatters: ChattersPanelChatter[];
  userInfoPopup: UserInfoPopupState | null;
  handleCloseUserInfo: () => void;
  popupChannelUrl: string;
  popupChannelLogin: string;
  popupProfileCover: string;
  popupProfileName: string;
  popupProfileAvatar: string;
  popupProfileLogin: string;
  popupProfileDescription: string;
  userInfoLoading: boolean;
  userInfoError: string;
  userModerationMessage: string;
  userInfoCanTimeout: boolean;
  userInfoCanBlock: boolean;
  moderationUnavailableReason: string;
  userModerationLoading: 'timeout' | 'block' | null;
  runModerationAction: (action: 'timeout' | 'block') => Promise<void>;
  userInfoResolvedUserId: string;
  userInfoIdCopied: boolean;
  copyUserInfoUserId: () => Promise<void>;
  userInfoCreatedAtLabel: string;
  userInfoFollowerCountLabel: string;
  userInfoTypeLabel: string;
  rawDataMessage: ChatMessage | null;
  rawDataJson: string;
  rawDataCopied: boolean;
  copyRawDataJson: () => Promise<void>;
  handleCloseRawData: () => void;
};
