// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Fax {
    /**
     * Creates a new Fax instance.
     * @param {Partial<Fax>} [$$source = {}] - The source object to create the Fax.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("UserName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UserName"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("ImageURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ImageURL"] = "";
        }
        if (!("AvatarURL" in $$source)) {
            /**
             * User avatar URL
             * @member
             * @type {string}
             */
            this["AvatarURL"] = "";
        }
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Timestamp"] = null;
        }
        if (!("ColorPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ColorPath"] = "";
        }
        if (!("MonoPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MonoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fax instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fax}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fax(/** @type {Partial<Fax>} */($$parsedSource));
    }
}
