version: "3"

tasks:
  # 開発モード
  dev:
    desc: 開発モードでアプリを起動（Tauri）
    cmds:
      - |
        echo "📦 OBS用オーバーレイをビルド中..."
        (cd web && bun run build)
        echo "🚀 cargo tauri dev を起動中..."
        cargo tauri dev

  dev:quick:
    desc: クイック開発モード（オーバーレイは事前ビルド前提）
    cmds:
      - cargo tauri dev

  # プロダクションビルド
  build:
    desc: プロダクションビルドを実行
    cmds:
      - echo "📦 OBS用オーバーレイをビルド中..."
      - cd web && bun run build
      - echo "🔨 Tauriアプリをビルド中..."
      - cargo tauri build
      - echo "✅ ビルド完了"

  # クリーンアップ
  clean:
    desc: ビルドファイルをクリーンアップ
    cmds:
      - echo "ビルドファイルをクリーンアップ中..."
      - rm -rf src-tauri/target
      - rm -rf frontend/dist
      - rm -rf web/dist
      - echo "クリーンアップ完了"

  # テスト実行
  test:
    desc: 全テストを実行
    env:
      DRY_RUN_MODE: "true"
    cmds:
      - echo "テストを実行中..."
      - cargo test

  # フロントエンド依存関係インストール
  install:
    desc: 全ての依存関係をインストール
    cmds:
      - echo "フロントエンドの依存関係をインストール中..."
      - cd frontend && bun install
      - echo "Webオーバーレイの依存関係をインストール中..."
      - cd web && bun install
      - echo "依存関係のインストール完了"

  i:
    desc: 全ての依存関係をインストール（短縮版）
    cmds:
      - task: install

  # クリーンインストール
  ci:
    desc: node_modulesを削除してクリーンインストール
    cmds:
      - echo "既存のnode_modulesを削除中..."
      - rm -rf frontend/node_modules web/node_modules
      - rm -f frontend/bun.lockb web/bun.lockb
      - echo "クリーンインストール実行中..."
      - cd frontend && bun install
      - cd web && bun install
      - echo "クリーンインストール完了"

  # 依存関係のアップデート
  update:
    desc: 全ての依存関係を最新版にアップデート
    cmds:
      - echo "フロントエンドの依存関係を更新中..."
      - cd frontend && bun update
      - echo "Webオーバーレイの依存関係を更新中..."
      - cd web && bun update
      - echo "Rust依存関係を更新中..."
      - cargo update
      - echo "依存関係の更新完了"
