version: "3"

tasks:
  # 開発モード
  dev:
    desc: Wails開発モードでアプリを起動（OBS用オーバーレイも同時ビルド）
    cmds:
      - echo "OBS用オーバーレイをビルド中..."
      - cd web && bun run build
      - echo "Wails開発モードを起動中..."
      - wails dev

  # プロダクションビルド
  build:
    desc: プロダクションビルドを実行
    cmds:
      - echo "OBS用オーバーレイをビルド中..."
      - cd web && bun run build
      - echo "プロダクションビルド中..."
      - wails build
      - echo "既存の署名を削除中..."
      - codesign --remove-signature build/bin/twitch-overlay.app
      - echo "新しい自己署名を適用中..."
      - codesign --force --deep --sign - build/bin/twitch-overlay.app
      - echo "ビルド完了 → build/bin/"

  # デバッグビルド
  build:debug:
    desc: デバッグビルドを実行
    cmds:
      - echo "OBS用オーバーレイをビルド中..."
      - cd web && bun run build
      - echo "デバッグビルド中..."
      - wails build -debug
      - echo "既存の署名を削除中..."
      - codesign --remove-signature build/bin/twitch-overlay.app
      - echo "新しい自己署名を適用中..."
      - codesign --force --deep --sign - build/bin/twitch-overlay.app
      - echo "デバッグビルド完了 → build/bin/"

  # クリーンアップ
  clean:
    desc: ビルドファイルをクリーンアップ
    cmds:
      - echo "ビルドファイルをクリーンアップ中..."
      - rm -rf build/bin
      - rm -rf frontend/dist
      - echo "クリーンアップ完了"

  # ビルド済みアプリケーションを実行
  run:
    desc: ビルド済みのアプリを実行
    cmds:
      - |
        if [ -f build/bin/twitch-overlay.app/Contents/MacOS/twitch-overlay ]; then
          open build/bin/twitch-overlay.app
        else
          echo "エラー: ビルド済みアプリが見つかりません"
          echo "先に 'task build' でビルドしてください"
          exit 1
        fi

  # テスト実行
  test:
    desc: 全テストを実行
    env:
      DRY_RUN_MODE: "true"
    cmds:
      - echo "テストを実行中..."
      - go test ./...

  # 配布用パッケージ作成（macOS）
  package:
    desc: 配布用パッケージを作成
    deps: [build]
    cmds:
      - echo "配布用パッケージを作成中..."
      - |
        if [ "$(uname)" = "Darwin" ]; then
          echo "macOS用のDMGを作成中..."
          # DMG作成コマンド（要追加）
          echo "TODO: DMG作成実装"
        else
          echo "現在のプラットフォームではパッケージ作成未対応"
        fi

  # フロントエンド依存関係インストール
  frontend:install:
    desc: フロントエンドの依存関係をインストール
    dir: frontend
    cmds:
      - bun install

  # 依存関係の一括インストール
  install:
    desc: 全ての依存関係をインストール
    cmds:
      - echo "フロントエンドの依存関係をインストール中..."
      - cd frontend && bun install
      - echo "Webオーバーレイの依存関係をインストール中..."
      - cd web && bun install
      - echo "依存関係のインストール完了"

  # 短縮コマンド
  i:
    desc: 全ての依存関係をインストール（短縮版）
    cmds:
      - task: install

  # クリーンインストール
  ci:
    desc: node_modulesを削除してクリーンインストール
    cmds:
      - echo "既存のnode_modulesを削除中..."
      - rm -rf frontend/node_modules web/node_modules
      - echo "bun.lockbを削除中..."
      - rm -f frontend/bun.lockb web/bun.lockb
      - echo "クリーンインストール実行中..."
      - cd frontend && bun install
      - cd web && bun install
      - echo "クリーンインストール完了"

  # 依存関係のアップデート
  update:
    desc: 全ての依存関係を最新版にアップデート
    cmds:
      - echo "フロントエンドの依存関係を更新中..."
      - cd frontend && bun update
      - echo "Webオーバーレイの依存関係を更新中..."
      - cd web && bun update
      - echo "依存関係の更新完了"

  # 依存関係の確認
  deps:
    desc: インストール済みの依存関係を確認
    cmds:
      - echo "=== Frontend Dependencies ==="
      - cd frontend && bun pm ls
      - echo ""
      - echo "=== Web Dependencies ==="
      - cd web && bun pm ls

  # Claude起動
  claude:
    desc: Claude起動
    cmds:
      - claude --dangerously-skip-permissions

  # バージョン情報表示
  version:
    desc: アプリケーションのバージョン情報を表示
    cmds:
      - |
        if [ -f build/bin/twitch-overlay.app/Contents/MacOS/twitch-overlay ]; then
          ./build/bin/twitch-overlay.app/Contents/MacOS/twitch-overlay --version
        else
          echo "バージョン: 開発版"
        fi
