import type { MutableRefObject } from 'react';
import type { Track, Playlist } from '@shared/types/music';
import type { DropdownDirection } from './types';

export interface MusicManagerController {
  tracks: Track[];
  playlists: Playlist[];
  selectedPlaylist: string | null;
  isUploadModalOpen: boolean;
  isCreatingPlaylist: boolean;
  newPlaylistName: string;
  isLoading: boolean;
  currentPage: number;
  showDeleteConfirm: boolean;
  playlistTracks: Track[];
  activeDropdown: string | null;
  addingToPlaylist: string | null;
  selectedTracks: string[];
  dropdownDirection: DropdownDirection;
  bulkAddingPlaylist: string | null;
  tracksPerPage: number;
  artworkUrls: Record<string, string>;
  displayTracks: Track[];
  currentTracks: Track[];
  totalPages: number;
  startIndex: number;
  endIndex: number;
  dropdownRefs: MutableRefObject<Record<string, HTMLDivElement | null>>;
  buttonRefs: MutableRefObject<Record<string, HTMLButtonElement | null>>;
  setSelectedPlaylist: (value: string | null) => void;
  setIsUploadModalOpen: (value: boolean) => void;
  setIsCreatingPlaylist: (value: boolean) => void;
  setNewPlaylistName: (value: string) => void;
  setCurrentPage: (value: number | ((current: number) => number)) => void;
  setShowDeleteConfirm: (value: boolean) => void;
  setActiveDropdown: (value: string | null) => void;
  setTracksPerPage: (value: number) => void;
  setSelectedTracks: (value: string[] | ((current: string[]) => string[])) => void;
  handleDeleteTrack: (trackId: string) => Promise<void>;
  handleDeleteAllTracks: () => Promise<void>;
  handleAddToPlaylist: (trackId: string, playlistId: string) => Promise<void>;
  handleCreatePlaylist: () => Promise<void>;
  handleUploadComplete: (track: Track) => void;
  handleSelectAll: () => void;
  handleSelectTrack: (trackId: string, shiftKey: boolean) => void;
  handleBulkAddToPlaylist: (playlistId: string) => Promise<void>;
  handleBulkDelete: () => Promise<void>;
  handleUploadClick: () => void;
  calculateDropdownPosition: (trackId: string) => void;
}
