[
    // --- FAX ---
    (
        "FAX_ENABLED",
        "true",
        false,
        false,
        "Enable FAX animation in overlay",
    ),
    (
        "FAX_ANIMATION_SPEED",
        "1.0",
        false,
        false,
        "FAX animation speed multiplier",
    ),
    (
        "FAX_IMAGE_TYPE",
        "color",
        false,
        false,
        "FAX image type (mono or color)",
    ),
    // --- Overlay display ---
    (
        "OVERLAY_CLOCK_ENABLED",
        "true",
        false,
        false,
        "Enable clock display in overlay",
    ),
    (
        "OVERLAY_CLOCK_FORMAT",
        "24h",
        false,
        false,
        "Clock format (12h or 24h)",
    ),
    (
        "LOCATION_ENABLED",
        "true",
        false,
        false,
        "Show location in overlay",
    ),
    ("DATE_ENABLED", "true", false, false, "Show date in overlay"),
    ("TIME_ENABLED", "true", false, false, "Show time in overlay"),
    (
        "OVERLAY_DEBUG_ENABLED",
        "false",
        false,
        false,
        "Enable debug panel in overlay",
    ),
    (
        "OVERLAY_CARDS_EXPANDED",
        r#"{"musicPlayer":true,"fax":true,"clock":true,"micTranscript":true,"rewardCount":true,"lottery":true}"#,
        false,
        false,
        "Overlay setting cards state",
    ),
    (
        "OVERLAY_CARDS_LAYOUT",
        r#"{"left":["musicPlayer","fax","clock","micTranscript"],"right":["rewardCount","lottery"]}"#,
        false,
        false,
        "Overlay setting cards layout",
    ),
    (
        "WORKSPACE_PAN_ON_SCROLL",
        "false",
        false,
        false,
        "Workspace scroll-to-pan mode",
    ),
    (
        "WORKSPACE_SCROLL_MODE_ENABLED",
        "false",
        false,
        false,
        "Enable workspace scroll mode (wheel to pan)",
    ),
    (
        "WORKSPACE_PAN_ACTIVATION_KEY",
        "Space",
        false,
        false,
        "Key code to activate canvas panning",
    ),
    (
        "WORKSPACE_ZOOM_MODIFIER_KEY",
        "Control",
        false,
        false,
        "Key code to activate canvas zoom passthrough",
    ),
    (
        "WORKSPACE_PREVIEW_PORTAL_ENABLED",
        "false",
        false,
        false,
        "Enable rendering workspace preview content through a body portal",
    ),
    // --- Reward count ---
    (
        "REWARD_COUNT_ENABLED",
        "false",
        false,
        false,
        "Enable reward count display",
    ),
    (
        "REWARD_COUNT_GROUP_ID",
        "",
        false,
        false,
        "Reward group ID to display",
    ),
    (
        "REWARD_COUNT_POSITION",
        "left",
        false,
        false,
        "Reward count position (left/right)",
    ),
]
