[
    // --- Mic transcript ---
    (
        "MIC_TRANSCRIPT_ENABLED",
        "false",
        false,
        false,
        "Enable mic transcript overlay",
    ),
    (
        "MIC_TRANSCRIPT_POSITION",
        "bottom-left",
        false,
        false,
        "Mic transcript position",
    ),
    (
        "MIC_TRANSCRIPT_V_ALIGN",
        "bottom",
        false,
        false,
        "Vertical alignment (top/bottom)",
    ),
    (
        "MIC_TRANSCRIPT_FRAME_HEIGHT_PX",
        "0",
        false,
        false,
        "Fixed frame height (0=auto)",
    ),
    (
        "MIC_TRANSCRIPT_FONT_SIZE",
        "20",
        false,
        false,
        "Mic transcript font size",
    ),
    (
        "MIC_TRANSCRIPT_MAX_LINES",
        "3",
        false,
        false,
        "Mic transcript max lines",
    ),
    (
        "MIC_TRANSCRIPT_MAX_WIDTH_PX",
        "0",
        false,
        false,
        "Max width px (0=unlimited)",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_LANGUAGE",
        "ja",
        false,
        false,
        "Speech API language code",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_ENABLED",
        "false",
        false,
        false,
        "Enable mic capture in WebUI",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_SHORT_PAUSE_MS",
        "750",
        false,
        false,
        "Short pause ms to flush",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_INTERIM_THROTTLE_MS",
        "200",
        false,
        false,
        "Interim throttle ms",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_DUAL_INSTANCE_ENABLED",
        "true",
        false,
        false,
        "Dual SpeechRecognition",
    ),
    (
        "MIC_TRANSCRIPT_SPEECH_RESTART_DELAY_MS",
        "100",
        false,
        false,
        "Restart delay ms",
    ),
    (
        "MIC_TRANSCRIPT_BOUYOMI_ENABLED",
        "false",
        false,
        false,
        "Enable BouyomiChan",
    ),
    (
        "MIC_TRANSCRIPT_BOUYOMI_URL",
        "http://localhost:50080",
        false,
        false,
        "BouyomiChan HTTP API URL",
    ),
    (
        "MIC_TRANSCRIPT_ANTI_SEXUAL_ENABLED",
        "false",
        false,
        false,
        "Enable content filter",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_ENABLED",
        "false",
        false,
        false,
        "Enable translation",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_MODE",
        "off",
        false,
        false,
        "Translation mode (off/chrome)",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_LANGUAGE",
        "en",
        false,
        false,
        "Target translation language",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_POSITION",
        "bottom-left",
        false,
        false,
        "Translation position",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_MAX_WIDTH_PX",
        "0",
        false,
        false,
        "Translation max width px",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_FONT_SIZE",
        "16",
        false,
        false,
        "Translation font size",
    ),
]
