[
    (
        "MIC_TRANSCRIPT_LINE_TTL_SECONDS",
        "8",
        false,
        false,
        "Line display duration (s)",
    ),
    (
        "MIC_TRANSCRIPT_LAST_TTL_SECONDS",
        "8",
        false,
        false,
        "Last line duration (0=inf)",
    ),
    (
        "MIC_TRANSCRIPT_TEXT_ALIGN",
        "",
        false,
        false,
        "Text alignment (empty=auto)",
    ),
    (
        "MIC_TRANSCRIPT_WHITE_SPACE",
        "",
        false,
        false,
        "CSS white-space",
    ),
    (
        "MIC_TRANSCRIPT_BACKGROUND_COLOR",
        "transparent",
        false,
        false,
        "Background color",
    ),
    (
        "MIC_TRANSCRIPT_TIMER_MS",
        "0",
        false,
        false,
        "Clear after inactivity (0=off)",
    ),
    (
        "MIC_TRANSCRIPT_INTERIM_MARKER_LEFT",
        " << ",
        false,
        false,
        "Interim left marker",
    ),
    (
        "MIC_TRANSCRIPT_INTERIM_MARKER_RIGHT",
        " >>",
        false,
        false,
        "Interim right marker",
    ),
    (
        "MIC_TRANSCRIPT_LINE_SPACING_1_PX",
        "0",
        false,
        false,
        "Spacing transcript-trans1",
    ),
    (
        "MIC_TRANSCRIPT_LINE_SPACING_2_PX",
        "0",
        false,
        false,
        "Spacing trans1-trans2",
    ),
    (
        "MIC_TRANSCRIPT_LINE_SPACING_3_PX",
        "0",
        false,
        false,
        "Spacing trans2-trans3",
    ),
    (
        "MIC_TRANSCRIPT_TEXT_COLOR",
        "#ffffff",
        false,
        false,
        "Transcript text color",
    ),
    (
        "MIC_TRANSCRIPT_STROKE_COLOR",
        "#000000",
        false,
        false,
        "Transcript stroke color",
    ),
    (
        "MIC_TRANSCRIPT_STROKE_WIDTH_PX",
        "6",
        false,
        false,
        "Transcript stroke width",
    ),
    (
        "MIC_TRANSCRIPT_FONT_WEIGHT",
        "900",
        false,
        false,
        "Transcript font weight",
    ),
    (
        "MIC_TRANSCRIPT_FONT_FAMILY",
        "Noto Sans JP",
        false,
        false,
        "Transcript font-family",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_TEXT_COLOR",
        "#ffffff",
        false,
        false,
        "Trans1 text color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_STROKE_COLOR",
        "#000000",
        false,
        false,
        "Trans1 stroke color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_STROKE_WIDTH_PX",
        "6",
        false,
        false,
        "Trans1 stroke width",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_FONT_WEIGHT",
        "900",
        false,
        false,
        "Trans1 font weight",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION_FONT_FAMILY",
        "Noto Sans JP",
        false,
        false,
        "Trans1 font-family",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_LANGUAGE",
        "",
        false,
        false,
        "Translation2 language",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_LANGUAGE",
        "",
        false,
        false,
        "Translation3 language",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_FONT_SIZE",
        "16",
        false,
        false,
        "Translation2 font size",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_FONT_SIZE",
        "16",
        false,
        false,
        "Translation3 font size",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_TEXT_COLOR",
        "#ffffff",
        false,
        false,
        "Trans2 text color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_STROKE_COLOR",
        "#000000",
        false,
        false,
        "Trans2 stroke color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_STROKE_WIDTH_PX",
        "6",
        false,
        false,
        "Trans2 stroke width",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_FONT_WEIGHT",
        "900",
        false,
        false,
        "Trans2 font weight",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION2_FONT_FAMILY",
        "Noto Sans JP",
        false,
        false,
        "Trans2 font-family",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_TEXT_COLOR",
        "#ffffff",
        false,
        false,
        "Trans3 text color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_STROKE_COLOR",
        "#000000",
        false,
        false,
        "Trans3 stroke color",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_STROKE_WIDTH_PX",
        "6",
        false,
        false,
        "Trans3 stroke width",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_FONT_WEIGHT",
        "900",
        false,
        false,
        "Trans3 font weight",
    ),
    (
        "MIC_TRANSCRIPT_TRANSLATION3_FONT_FAMILY",
        "Noto Sans JP",
        false,
        false,
        "Trans3 font-family",
    ),
]
