[
    // --- Lottery ---
    (
        "LOTTERY_ENABLED",
        "false",
        false,
        false,
        "Enable lottery/roulette feature",
    ),
    (
        "LOTTERY_REWARD_ID",
        "",
        false,
        false,
        "Target reward ID for lottery",
    ),
    (
        "LOTTERY_LOCKED",
        "false",
        false,
        false,
        "Whether lottery is locked",
    ),
    (
        "LOTTERY_DISPLAY_DURATION",
        "5",
        false,
        false,
        "Lottery display duration (s)",
    ),
    (
        "LOTTERY_ANIMATION_SPEED",
        "1.0",
        false,
        false,
        "Lottery animation speed",
    ),
    (
        "LOTTERY_TICKER_ENABLED",
        "false",
        false,
        false,
        "Enable lottery participant ticker",
    ),
    // --- Ticker notice ---
    (
        "TICKER_NOTICE_ENABLED",
        "false",
        false,
        false,
        "Enable ticker notice display",
    ),
    (
        "TICKER_NOTICE_TEXT",
        "",
        false,
        false,
        "Ticker notice text content",
    ),
    (
        "TICKER_NOTICE_FONT_SIZE",
        "16",
        false,
        false,
        "Ticker notice font size",
    ),
    (
        "TICKER_NOTICE_ALIGN",
        "center",
        false,
        false,
        "Ticker notice alignment",
    ),
    // --- Notification ---
    (
        "NOTIFICATION_ENABLED",
        "true",
        false,
        false,
        "Enable chat notification window",
    ),
    (
        "NOTIFICATION_WINDOW_X",
        "",
        false,
        false,
        "Notification window X",
    ),
    (
        "NOTIFICATION_WINDOW_Y",
        "",
        false,
        false,
        "Notification window Y",
    ),
    (
        "NOTIFICATION_WINDOW_WIDTH",
        "400",
        false,
        false,
        "Notification window width",
    ),
    (
        "NOTIFICATION_WINDOW_HEIGHT",
        "150",
        false,
        false,
        "Notification window height",
    ),
    (
        "NOTIFICATION_WINDOW_ABSOLUTE_X",
        "",
        false,
        false,
        "Notification absolute X",
    ),
    (
        "NOTIFICATION_WINDOW_ABSOLUTE_Y",
        "",
        false,
        false,
        "Notification absolute Y",
    ),
    (
        "NOTIFICATION_WINDOW_SCREEN_INDEX",
        "0",
        false,
        false,
        "Notification screen index",
    ),
    (
        "NOTIFICATION_WINDOW_SCREEN_HASH",
        "",
        false,
        false,
        "Notification screen hash",
    ),
    (
        "NOTIFICATION_WINDOW_MOVABLE",
        "true",
        false,
        false,
        "Allow moving notification window",
    ),
    (
        "NOTIFICATION_WINDOW_RESIZABLE",
        "true",
        false,
        false,
        "Allow resizing notification window",
    ),
    (
        "NOTIFICATION_DISPLAY_DURATION",
        "5",
        false,
        false,
        "Notification duration (s)",
    ),
    (
        "NOTIFICATION_DISPLAY_MODE",
        "queue",
        false,
        false,
        "Notification mode (queue/overwrite)",
    ),
    (
        "NOTIFICATION_FONT_SIZE",
        "14",
        false,
        false,
        "Notification font size",
    ),
]
