[
    // --- Twitch secrets ---
    ("CLIENT_ID", "", true, true, "Twitch API Client ID"),
    ("CLIENT_SECRET", "", true, true, "Twitch API Client Secret"),
    (
        "TWITCH_USER_ID",
        "",
        true,
        true,
        "Twitch User ID for monitoring",
    ),
    (
        "TRIGGER_CUSTOM_REWORD_ID",
        "",
        true,
        true,
        "Custom Reward ID for triggering FAX",
    ),
    // --- Printer ---
    (
        "PRINTER_TYPE",
        "bluetooth",
        false,
        false,
        "Printer type (bluetooth or usb)",
    ),
    (
        "PRINTER_ADDRESS",
        "",
        false,
        true,
        "Bluetooth MAC address of the printer",
    ),
    (
        "USB_PRINTER_NAME",
        "",
        false,
        false,
        "System printer name for USB printing",
    ),
    (
        "DRY_RUN_MODE",
        "true",
        false,
        false,
        "Enable dry run mode (no actual printing)",
    ),
    (
        "BEST_QUALITY",
        "true",
        false,
        false,
        "Enable best quality printing",
    ),
    ("DITHER", "true", false, false, "Enable dithering"),
    (
        "BLACK_POINT",
        "0.5",
        false,
        false,
        "Black point threshold (0.0-1.0)",
    ),
    ("AUTO_ROTATE", "false", false, false, "Auto rotate images"),
    (
        "ROTATE_PRINT",
        "true",
        false,
        false,
        "Rotate print output 180 degrees",
    ),
    // --- Operation ---
    (
        "KEEP_ALIVE_INTERVAL",
        "60",
        false,
        false,
        "Keep alive interval in seconds",
    ),
    (
        "KEEP_ALIVE_ENABLED",
        "false",
        false,
        false,
        "Enable keep alive functionality",
    ),
    (
        "CLOCK_ENABLED",
        "false",
        false,
        false,
        "Enable clock printing",
    ),
    (
        "CLOCK_SHOW_ICONS",
        "true",
        false,
        false,
        "Show icons in clock display",
    ),
    ("DEBUG_OUTPUT", "false", false, false, "Enable debug output"),
    (
        "TIMEZONE",
        "Asia/Tokyo",
        false,
        false,
        "Timezone for clock display",
    ),
    (
        "AUTO_DRY_RUN_WHEN_OFFLINE",
        "false",
        false,
        false,
        "Auto dry-run when stream offline",
    ),
    // --- Server ---
    (
        "SERVER_PORT",
        "8080",
        false,
        false,
        "Web server port for WebUI and OBS overlay",
    ),
    // --- Font ---
    ("FONT_FILENAME", "", false, false, "Uploaded font file name"),
    // --- Window ---
    ("WINDOW_X", "", false, false, "Window X position"),
    ("WINDOW_Y", "", false, false, "Window Y position"),
    ("WINDOW_WIDTH", "1024", false, false, "Window width"),
    ("WINDOW_HEIGHT", "768", false, false, "Window height"),
    (
        "WINDOW_FULLSCREEN",
        "false",
        false,
        false,
        "Window fullscreen state",
    ),
    (
        "WINDOW_SCREEN_HASH",
        "",
        false,
        false,
        "Screen configuration hash",
    ),
    (
        "WINDOW_ABSOLUTE_X",
        "",
        false,
        false,
        "Window absolute X position",
    ),
    (
        "WINDOW_ABSOLUTE_Y",
        "",
        false,
        false,
        "Window absolute Y position",
    ),
    (
        "WINDOW_SCREEN_INDEX",
        "0",
        false,
        false,
        "Screen index where window is located",
    ),
    (
        "WINDOW_STATE_JSON",
        "",
        false,
        false,
        "Window state as JSON",
    ),
    (
        "TRAY_SETTINGS_WINDOW_X",
        "",
        false,
        false,
        "Tray settings window X position",
    ),
    (
        "TRAY_SETTINGS_WINDOW_Y",
        "",
        false,
        false,
        "Tray settings window Y position",
    ),
    (
        "TRAY_SETTINGS_WINDOW_WIDTH",
        "460",
        false,
        false,
        "Tray settings window width",
    ),
    (
        "TRAY_SETTINGS_WINDOW_HEIGHT",
        "320",
        false,
        false,
        "Tray settings window height",
    ),
    // --- Music ---
    (
        "MUSIC_ENABLED",
        "true",
        false,
        false,
        "Enable music player in overlay",
    ),
    ("MUSIC_VOLUME", "70", false, false, "Music volume (0-100)"),
    (
        "MUSIC_PLAYLIST",
        "",
        false,
        false,
        "Selected music playlist",
    ),
    (
        "MUSIC_AUTO_PLAY",
        "false",
        false,
        false,
        "Auto play music on startup",
    ),
]
