// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * StreamStatus represents the current stream status
 */
export class StreamStatus {
    /**
     * Creates a new StreamStatus instance.
     * @param {Partial<StreamStatus>} [$$source = {}] - The source object to create the StreamStatus.
     */
    constructor($$source = {}) {
        if (!("is_live" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_live"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["started_at"] = undefined;
        }
        if (!("viewer_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["viewer_count"] = 0;
        }
        if (!("last_checked" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["last_checked"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamStatus(/** @type {Partial<StreamStatus>} */($$parsedSource));
    }
}
