// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Playlist {
    /**
     * Creates a new Playlist instance.
     * @param {Partial<Playlist>} [$$source = {}] - The source object to create the Playlist.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("track_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["track_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Playlist}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist(/** @type {Partial<Playlist>} */($$parsedSource));
    }
}

export class PlaylistTrack {
    /**
     * Creates a new PlaylistTrack instance.
     * @param {Partial<PlaylistTrack>} [$$source = {}] - The source object to create the PlaylistTrack.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("has_artwork" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_artwork"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTrack(/** @type {Partial<PlaylistTrack>} */($$parsedSource));
    }
}
