// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {music} from '../models';
import {faxmanager} from '../models';
import {frontend} from '../models';
import {main} from '../models';
import {status} from '../models';
import {embed} from '../models';

export function AddTrackToPlaylist(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ClearAllCache():Promise<void>;

export function ConnectPrinter(arg1:string):Promise<void>;

export function CreateMusicPlaylist(arg1:string,arg2:string):Promise<music.Playlist>;

export function DeleteFont():Promise<void>;

export function DeleteMusicPlaylist(arg1:string):Promise<void>;

export function DeleteMusicTrack(arg1:string):Promise<void>;

export function DisconnectPrinter():Promise<void>;

export function GenerateFontPreview(arg1:string):Promise<string>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetAuthURL():Promise<string>;

export function GetCacheSettings():Promise<Record<string, any>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetEventSubStatus():Promise<Record<string, any>>;

export function GetFeatureStatus():Promise<Record<string, any>>;

export function GetMusicPlaylists():Promise<Record<string, any>>;

export function GetMusicTracks():Promise<Record<string, any>>;

export function GetPlaylistTracks(arg1:string):Promise<Array<music.PlaylistTrack>>;

export function GetPrinterStatus():Promise<Record<string, any>>;

export function GetRecentFaxes(arg1:number):Promise<Array<faxmanager.Fax>>;

export function GetScreens():Promise<Array<frontend.Screen>>;

export function GetScreensExtended():Promise<Array<main.ScreenInfoExtended>>;

export function GetServerPort():Promise<number>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetStreamStatus():Promise<status.StreamStatus>;

export function GetTrackArtwork(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function GetWindowPosition():Promise<Record<string, number>>;

export function HandleAuthCallback(arg1:string):Promise<void>;

export function ReconnectPrinter():Promise<void>;

export function RemoveTrackFromPlaylist(arg1:string,arg2:string):Promise<void>;

export function RunCacheCleanup():Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScanBluetoothDevices():Promise<Array<Record<string, any>>>;

export function SetWebAssets(arg1:embed.FS):Promise<void>;

export function TestChannelPointRedemption(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestPrint():Promise<void>;

export function UpdateCacheSettings(arg1:Record<string, any>):Promise<void>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function UploadFont(arg1:string,arg2:string):Promise<void>;
