// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrackToPlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTrackToPlaylist'](arg1, arg2, arg3);
}

export function ConnectPrinter(arg1) {
  return window['go']['main']['App']['ConnectPrinter'](arg1);
}

export function CreateMusicPlaylist(arg1, arg2) {
  return window['go']['main']['App']['CreateMusicPlaylist'](arg1, arg2);
}

export function DeleteFont() {
  return window['go']['main']['App']['DeleteFont']();
}

export function DeleteMusicPlaylist(arg1) {
  return window['go']['main']['App']['DeleteMusicPlaylist'](arg1);
}

export function DeleteMusicTrack(arg1) {
  return window['go']['main']['App']['DeleteMusicTrack'](arg1);
}

export function DisconnectPrinter() {
  return window['go']['main']['App']['DisconnectPrinter']();
}

export function GenerateFontPreview(arg1) {
  return window['go']['main']['App']['GenerateFontPreview'](arg1);
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAuthURL() {
  return window['go']['main']['App']['GetAuthURL']();
}

export function GetEventSubStatus() {
  return window['go']['main']['App']['GetEventSubStatus']();
}

export function GetFeatureStatus() {
  return window['go']['main']['App']['GetFeatureStatus']();
}

export function GetMusicPlaylists() {
  return window['go']['main']['App']['GetMusicPlaylists']();
}

export function GetMusicTracks() {
  return window['go']['main']['App']['GetMusicTracks']();
}

export function GetPlaylistTracks(arg1) {
  return window['go']['main']['App']['GetPlaylistTracks'](arg1);
}

export function GetPrinterStatus() {
  return window['go']['main']['App']['GetPrinterStatus']();
}

export function GetRecentFaxes(arg1) {
  return window['go']['main']['App']['GetRecentFaxes'](arg1);
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStreamStatus() {
  return window['go']['main']['App']['GetStreamStatus']();
}

export function GetTrackArtwork(arg1) {
  return window['go']['main']['App']['GetTrackArtwork'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HandleAuthCallback(arg1) {
  return window['go']['main']['App']['HandleAuthCallback'](arg1);
}

export function ReconnectPrinter() {
  return window['go']['main']['App']['ReconnectPrinter']();
}

export function RemoveTrackFromPlaylist(arg1, arg2) {
  return window['go']['main']['App']['RemoveTrackFromPlaylist'](arg1, arg2);
}

export function RestartWebServer(arg1) {
  return window['go']['main']['App']['RestartWebServer'](arg1);
}

export function ScanBluetoothDevices() {
  return window['go']['main']['App']['ScanBluetoothDevices']();
}

export function SetWebAssets(arg1) {
  return window['go']['main']['App']['SetWebAssets'](arg1);
}

export function TestPrint() {
  return window['go']['main']['App']['TestPrint']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UploadFont(arg1, arg2) {
  return window['go']['main']['App']['UploadFont'](arg1, arg2);
}
